pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: ./models/torch/pyannote/speechbrain
    embedding_batch_size: 8
    embedding_exclude_overlap: False
    segmentation: ./models/pytorch_model.bin
    segmentation_batch_size: 8

params:
  clustering:
    method: centroid
    min_cluster_size: 15
    threshold: 0.7153814381597874
  segmentation:
    min_duration_off: 0.5817029604921046
    threshold: 0.4442333667381752
